Document: wicotorenuei
Title: Debian wicotorenuei Manual
Author: <insert document author here>
Abstract: This manual describes what wicotorenuei is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wicotorenuei/wicotorenuei.sgml.gz

Format: postscript
Files: /usr/share/doc/wicotorenuei/wicotorenuei.ps.gz

Format: text
Files: /usr/share/doc/wicotorenuei/wicotorenuei.text.gz

Format: HTML
Index: /usr/share/doc/wicotorenuei/html/index.html
Files: /usr/share/doc/wicotorenuei/html/*.html

  
